### ISSUE TITLE
Review Temporal Pooler and improve documentation etc.

### ISSUE THREAD

**Issue by rmccall84** [numenta/nupic.research#126]
As part of my task to implement online temporal pooling, I have been reviewing the temporal pooler. Since I don't know all the terminology used in this code, I can help improve the documentation and variable names. There are a few issues / improvements I think I have found too.

**Comment by rmccall84** [comment]
@scottpurdy If this sounds good to you, I can start a PR. Implementing the online pooling is a big task so I'm trying to break it up.

**Comment by scottpurdy** [comment]
@rmccall84 - perhaps you could create a task with the different steps broken down in a list first and then create issues for each step once you get buy in? Just looking at this issue alone doesn't give me a sense of how you are breaking up the project. But it does seem like a good first step.
