### ISSUE TITLE
Implement Online Temporal Pooling

### ISSUE THREAD

**Issue by rmccall84** [numenta/nupic.research#127]
The current implementation of Temporal Pooling is not truly online. For instance, the capacity experiment first runs the Temporal Memory and Temporal Pooler with only the TM learning, then it runs them again with only the TP learning. (I think @chetan51 said that it was hard to obtain stability if both learned in tandem). Ideally both the TM and the TP would both learn at the same time. 

Since this is a complex task, I propose breaking it down into the following steps:

- [x] How will we measure performance? In terms of "stability confusion" and "distinctness confusion" as in the capacity experiment.
- [ ] Being unfamiliar with the TP, I will review it and help improve the documentation and variable names, and I will also focus on the learning algorithm. This should greatly help future newbies. There are a few issues and improvements I want to discuss. 
Sub-issue: https://github.com/numenta/nupic.research/issues/126
- [ ] Likewise, review TM improving the documentation and description. 
- [x] Extend capacity experiment to optionally test online learning in the TP. Evaluate new code using metrics defined in first item. 
Sub-issue: https://github.com/numenta/nupic.research/pull/135

I'd appreciate your feedback and/or current ideas about how online temporal pooling might happen.

Thank you!

**Comment by chetan51** [comment]
> 1.) Supposing that an online version is prototyped, how will we convince ourselves it is as good as the current 2-pass method? How will we measure performance? In terms of "stability confusion" and "distinctness confusion" using the capacity experiment?

Yes. We should get as good results with the capacity experiments.

**Comment by rmccall84** [comment]
Detailed Experiment Plan (2.13.15)

1.) Rerun: Vary elements, strict, 10x-slower []

Continue testing slow TP learning (3x and 10x slower)
2.) Vary elements, strict []
3.) Vary elements, reasonable []
4.) Vary world size, strict []
5.) Vary world size, reasonable []

6.) Decrease effort in turning file output into plot images []
a.) Extend run to create a single csv file containing results of each def (worlds-elements pair)
b.) Write a script that takes a two numbers representing columns in the CSV and plots specified x,y data in matplotlib
i.) Extend to a list of plot columns
ii.) Add standard deviation plotting

7.) Produce summary including axis labels and the max of two metrics. []

**Comment by scottpurdy** [comment]
@rmccall84 - let's discuss Monday
