### ISSUE TITLE
Problem about classification of MNSIT dataset

### ISSUE THREAD

**Issue by tsenggordon** [numenta/nupic.research#143]
Dear all
    I' m trying use HTM spatial pooler as a feature extractor on image recognition problem. Now I use 
MNIST dataset to be a start point. As far as I now, the input of spatial pooler should be binary data, but
 the range of  MNIST pixel value is from 0 to 255. I wonder how we convert that value to a binary input. 
(filter the pixel value to be 0 or 1 by a threshold? or just use the binary system to represent the pixel 
value? (28x28x8?))

**Comment by cogmission** [comment]
Hi!

I believe This repository is a bleeding edge repository (for research only and provided as a courtesy) and is not supported, therefore you cannot open issues regarding this code.

**Comment by breznak** [comment]
I think it's fine to open issues and ask, just you might not always get an
answer.

Have a look in the nupic.vision repo, there's an ImageRegion that serves as
an encoder for image data. Anyways, I think both mentioned approaches would
be interesting to try out.

* 0/1 threshold - has a significant loss of information in the color domain
* 28x28x8 - on the other hands breaks the spatial property of the
neighboring bits

So... personaly I'd think the B/W reduction would work quite well for
MNIST.

**Comment by scottpurdy** [comment]
@tsenggordon feel free to look at the image sensor for how it handles images:
https://github.com/numenta/nupic/blob/master/nupic/regions/ImageSensor.py
