### ISSUE TITLE
Please document your projects

### ISSUE THREAD

**Issue by breznak** [numenta/nupic.research#289]
Guys, 
for an on-looker here, it's quite a hard work to get a meaning of the existing experiments. It would be nice if each experiment contained a `Readme` with a few sentences: what is the experiment covering, what parts of HTM is it stressing, what is the current status (eg not working at all) and how the results seem. Personal opinion is just fine :) 

CC @rhyolight

**Comment by rhyolight** [comment]
:+1: @numenta/research I agree that a `README` with a few descriptive lines about each project would be quite helpful to all involved. I've been getting more requests for us to provide some basic documentation for the sensorimotor code in preparation for the upcoming HTM Challenge.

**Comment by subutai** [comment]
@breznak Good feedback - we'll try to do that better. It's a bit hard as we change things often and most of the experiments are abandoned (hey, that's part of doing research :-).  Maybe we can do a better job documenting something once a project stabilizes a bit.

**Comment by subutai** [comment]
We've started documenting a bit better and will try our best. But please see the disclaimer in the README too!
