### ISSUE TITLE
Convert sequence_learning to new TM

### ISSUE THREAD

**Issue by subutai** [numenta/nupic.research#601]
The sequence learning script in https://github.com/numenta/nupic.research/tree/master/projects/sequence_learning is referenced by the Neuron paper and uses the class FaultyTemporalMemory, which subclasses from the old phases temporal memory implementation. We want to get rid of the various phases implementations.

FaultyTemporalMemory is also used in @ywcui1990's scripts used in the sequence memory paper.

This issue is to convert the sequence learning script to use some derivative of the new temporal memory (subclassed or not, it doesn't matter) and obtain essentially identical results in the two scripts.

Completion of this task includes convincing Subutai and Yuwei that the new implementation is essentially identical and then removing the old faulty temporal memory from the repository.

**Comment by oxtopus** [comment]
@subutai re:

> then removing the old faulty temporal memory from the repository

The script has "killer" and "killingMeSoftly" options which depend on functionality exclusive to `FaultyTemporalMemory`.  Shall that functionality be preserved, somehow, or removed along with `FaultyTemporalMemory`?

**Comment by oxtopus** [comment]
After discussing w/ @subutai and @mrcslws, I'm putting this in a blocked state until we can diagnose why the current implementation doesn't produce results that are consistent with the paper.

**Comment by oxtopus** [comment]
@subutai, @ywcui1990, @mrcslws: This one's ready for another review at https://github.com/numenta/nupic.research/pull/637

**Comment by oxtopus** [comment]
`FaultyTemporalMemory` is now subclassing `nupic.research.temporal_memory.TemporalMemory` (https://github.com/numenta/nupic.research/blob/master/htmresearch/algorithms/faulty_temporal_memory.py#L30) and the implementation reduces overhead by only subclassing the public `TemporalMemory.burstColumn()`.
