### ISSUE TITLE
Python3 error in projects/location_layer/single_layer_2d_experiment/logging.py

### ISSUE THREAD

**Issue by fcr** [numenta/nupic.research#660]
projects/location_layer/single_layer_2d_experiment/logging.py Line 223:
            
`activeColumn = cell / self.inputLayer.cellsPerColumn`

should read:

`activeColumn = cell // self.inputLayer.cellsPerColumn`

**Comment by mrcslws** [comment]
Nice catch! There were a bunch of these in the Python 2 -> 3 transition, looks like I still missed a few.
