### ISSUE TITLE
Implement pooling region

### ISSUE THREAD

**Issue by subutai** [numenta/nupic.research#69]
Union pooler:
https://github.com/numenta/nupic.research/tree/master/union_pooling

This would be nice to support as a follow on:
https://github.com/numenta/nupic.research/blob/master/sensorimotor/sensorimotor/temporal_pooler.py

**Comment by scottpurdy** [comment]
@akhilaananthram - This could be a good follow up task to the pluggable regions work in nupic and nupic.core
