### ISSUE TITLE
Update sm_1d_test to use Monitor Mixin

### ISSUE THREAD

**Issue by chetan51** [numenta/nupic.research#75]
It's currently using the old `TemporalMemoryInspectMixin`.

**Comment by BoltzmannBrain** [comment]
I think sm_1d_test may need an overhaul to incorporate the following:
- [ ] `MonitorMixinBase` or `TemporalMemoryMonitorMixin`; this would fix the broken code in issue #149 
- [ ] `SensorimotorExperimentRunner`
@chetan51 what do you think?

**Comment by chetan51** [comment]
I'm not sure whether those tests are still valuable or not. Probably a question for @subutai, who I believe wrote some of them.

**Comment by subutai** [comment]
I'm fine if we delete it. I don't have any long term allegiance to research code. It's actually easier if we have fewer unit tests and only write those that help us debug the functionality.

**Comment by BoltzmannBrain** [comment]
Sounds good to me. I'll delete it in my next push for #149.
